version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hanzo
      MYSQL_USER: hanzo
      MYSQL_PASSWORD: 15112002
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
